const meals = [
    { id: 1, 
        category: 'nuevas gotas', 
        name: 'Pie de Manzana', 
        filter: 'Rápido', 
        tipo: 'Dulce',
        ingredientes: 'Pasteleria',
        image: require('../../assets/img/apple-pie.jpg'),
        descripcion: 'Las manzanas en escabeche son un ingrediente versátil que puede agregar un toque único a platos dulces y salados. Su perfil de sabor picante y ligeramente dulce los convierte en una excelente adición a diversas recetas, desde ensaladas hasta tablas de quesos, realzando platos con un sabor y textura distintivos.',
        preparacion: ['Manzana', 'Azúcar', 'Sal', 'Vinagre de alcohol', 'Agua'],  
    },
    { id: 2, 
        category: 'nuevas gotas', 
        name: 'Estofado de carne', 
        filter: 'Fácil',
        tipo: 'Almuerzo',
        ingredientes: 'Carne',
        image: require('../../assets/img/estofadoCarne.jpg'),
        descripcion: 'Este Guiso de Carne Brasileño conocido como “picadinho” es un clásico que nunca pasa de moda. Normalmente se sirve con arroz blanco y es un plato perfecto para compartir con amigos o familiares en casa.',
        preparacion: ['Solomillo de ternera', 'Cebolla', 'Ajo', 'Aceite de oliva', 'Puré de tomate', 'Perejil', 'Sal', 'Pimienta negra'], 
    },
    { id: 3, 
        category: 'nuevas gotas', 
        name: 'Rapscallion',
        filter: '1h o menos' , 
        tipo: 'Cocteles',
        image: require('../../assets/img/cocktail.jpg'),
        descripcion: '¡Aprende cómo hacer un Manhattan con un toque diferente!',
        preparacion: ['Whisky de pura malta', 'Pastis', 'Limon', 'Hielo'], 
    },
    { id: 4, 
        category: 'nuevas gotas', 
        name: 'Carpaccio', 
        filter: 'Desafio', 
        tipo: 'Desayuno', 
        ingredientes: ['Queso', 'Carne'],
        image: require('../../assets/img/carpaccio.jpg') ,
        descripcion: '¡Una versión del carpaccio con sabores frescos e influencias asiáticas. El plato perfecto para invitar a amigos o como entrante de una cena impresionante. Acompáñalo con ensalada de rúcula y unas tostadas y disfrútalo. Puedes utilizar el lomo de res sobrante en otras recetas, como filete al poivre, estofado de ternera o cualquier otro plato de tu elección. Solo asegúrate de no volver a congelarlo. Si quieres ponértelo aún más fácil, puedes comprar carne ya cortada.',
        preparacion: ['Solomillo De Ternera', 'Jengibre en escabeche', 'Cebollas Crujientes', 'Pimienta negra', 'Aceite de oliva virgen extra', 'Sal'], 
    },
    { id: 5, 
        category: 'nuevas gotas', 
        name: 'Puré de papas', 
        filter: 'Pocos ingredientes',
        tipo: 'Cena', 
        ingredientes: 'Papa',
        image: require('../../assets/img/purePapa.jpg') ,
        descripcion: 'Una receta buena y honesta de puré de papas. No tiene que ser sofisticado ni suave, ¡pero tiene que ser sabroso! Puedes cortar las patatas en cubos más pequeños para facilitar la cocción.',
        preparacion: ['Papa', 'Leche', 'Sal', 'Manteca', 'Agua'], 
    },

    {
        id: 6,
        category: 'menos de 30m', 
        name: 'Tortilla de papas', 
        filter: 'Rápido', 
        tipo: 'Almuerzo',
        ingredientes: ['Papa', 'Huevo'],
        image: require('../../assets/img/tortilla.jpg') ,
        descripcion: '¡Aprende cómo hacer una tortilla de papa bien Argenta, con un toque diferente!',
        preparacion: ['Papa', 'Huevo', 'Aceite', 'Orégano'], 
    },
    {
        id: 7,
        category: 'menos de 30m', 
        name: 'Papas fritas', 
        filter: 'Pocos ingredientes', 
        tipo: 'Cena',
        ingredientes: 'Papa',
        image: require('../../assets/img/papasFritas.jpg') ,
        descripcion: 'Las papas fritas, también conocidas como papas fritas o palitos de papa, son un tipo de papa frita que es muy delgada y se asemeja a palitos pequeños y delgados. A menudo se sirven como refrigerio o guarnición.',
        preparacion: ['Papa', 'Aceite'],
    },
    {
        id: 8,
        category: 'menos de 30m', 
        name: 'Spaghetti', 
        filter: 'Pocos ingredientes', 
        tipo: 'Cena',
        ingredientes: 'Pasta',
        image: require('../../assets/img/spaghetti.jpg') ,
        descripcion: 'El símbolo de Roma, con la magia hecha de queso pecorino, guanciale y yemas de huevo que hace que un plato de pasta sea cremoso y crujiente al mismo tiempo. Los espaguetis a la carbonara son un plato reconfortante y saciante, perfecto para cualquier época del año. ¡Funciona para el almuerzo o la cena y combina perfectamente con una copa de vino! Si no encuentra guanciale, sustitúyalo por su cerdo curado favorito.',
        preparacion: ['Espaguetis', 'Guanciale', 'Queso pecorino', 'Huevo', 'Pimienta negro', 'Sal'],
    },
    {
        id: 9,
        category: 'menos de 30m', 
        name: 'Caipirinha', 
        filter: 'Desafio', 
        tipo: 'Cocteles',
        image: require('../../assets/img/caipirinha.jpg') ,
        descripcion: 'El sabor de Brasil, con mucho limón y una cachaça ligeramente endulzada. Súper fácil de hacer y maravilloso. Puedes utilizar cualquier edulcorante en lugar del almíbar simple. ¿Quieres hacer tu propio almíbar sencillo? ¡Encuéntralo aquí en CREMA! El ingrediente más importante es el amor brasileño.',
        preparacion: ['Limpiar cachaza', 'Jarabe sencillo', 'Cal', 'Limón', 'Hielo'],
    },

    {
        id: 10,
        category: 'salsas picantes', 
        name: 'Taperu Rayu', 
        filter: 'Rápido', 
        tipo: 'Almuerzo',
        image: require('../../assets/img/salsa1.jpg') ,
        descripcion: '¡Un aceite de chile japonés tradicional que agregará picante y sabor a cualquier cosa que le agregues!',
        preparacion: ['Hojuelas de chile rojo', 'Almendra tostada y picada', 'Semillas de sésamo tostadas', 'Hojuelas de cebolla seca', 'Hojuelas de ajo seco', 'Salsa de soja', 'Aceite vegetal', 'Sal'],
    },
    {
        id: 11,
        category: 'salsas picantes', 
        name: 'Salsa macha', 
        filter: 'Fácil',
        tipo: 'Cena',
        image: require('../../assets/img/salsa2.jpg') ,
        descripcion: 'Esta receta mexicana de Salsa Macha es el condimento perfecto. Está elaborado con trocitos crujientes de chile tostado, ajo, anacardos y "nuez de barú", nuestra adición especial brasileña, y aceite. ¡Combina perfectamente con mariscos crudos, verduras asadas o cualquier plato que necesite un toque picante y complejo! ¡Básicamente puedes colocarlo sobre todo! Esta está basada en una receta clásica mexicana pero hecha con las mejores nueces brasileñas.',
        preparacion: ['Chile guajillo', 'Chile Pasilla', 'Chile Morita', 'Anacardo', 'Nuez de Barú', 'Aceite vegetal', 'Ajo'],
    },
    {
        id: 12,
        category: 'salsas picantes', 
        name: 'Aloo tuk', 
        filter: 'Pocos ingredientes', 
        tipo: 'Cena',
        ingredientes: 'Papa',
        image: require('../../assets/img/salsa3.jpg') ,
        descripcion: '¡Aloo Tuk es un puré de papas crujiente y tierno, frito dos veces y con un toque de mezcla de especias! Las especias se pueden cambiar por cualquier cosa que tengas a mano, o cualquiera que sea tu mezcla de especias favorita, pero el amchur, o polvo de mango seco, marca la diferencia aquí. Si lo encuentra en una tienda india especializada, probablemente será una valiosa adición a su despensa. Aloo Tuk, es un plato muy popular en toda la diáspora sindhi, muy a menudo un alimento básico en los almuerzos de los domingos en los hogares sindhi.',
        preparacion: ['Papa', 'Amchur', 'Chile Morita', 'Chile en polvo', 'Polvo de semilla de cilantro', 'Aceite vegetal', 'Sal'],
    
    },

    {
        id: 13,
        category: 'postres', 
        name: 'Galletas de manteca', 
        filter: 'Desafio', 
        tipo: 'Dulce',
        ingredientes: 'Pasteleria',
        image: require('../../assets/img/galletasManteca.jpg') ,
        descripcion: '¡Esta receta es perfecta para hacer galletas navideñas y es divertida para toda la familia. ¡Sencillo, delicioso y rápido!',
        preparacion: ['Vainilla', 'Harina para todo uso', 'Manteca', 'Azucar blanca'],
    
    },
    {
        id: 14,
        category: 'postres', 
        name: 'Chocotorta', 
        filter: 'Pocos ingredientes',
        tipo: 'Dulce',
        ingredientes: 'Pasteleria', 
        image: require('../../assets/img/chocotorta.jpg') ,
        descripcion: '¡Esta receta es perfecta para hacer disfrutar y es divertida para toda la familia. ¡Sencillo, delicioso y rápido!',
        preparacion: ['Galletas', 'Leche', 'Cafe', 'Quesso crema', 'Dulde de leche'],
    
    },
    {
        id: 15,
        category: 'postres', 
        name: 'Galletas de chocolate', 
        filter: 'Fácil', 
        tipo: 'Dulce',
        ingredientes: 'Pasteleria',
        image: require('../../assets/img/galletasChoco.jpg') ,
        descripcion: '¡Súper fácil y rápido de hacer, no hay nada mejor que esto. ¡Pruébalas y te convencerás también!',
        preparacion: ['Chocolate 50% Cacao', 'Manteca', 'Levadura en polvo', 'Azucar blanca', 'Harina para todo uso', 'Huevo'],
    
    },
    {
        id: 16,
        category: 'postres', 
        name: 'Alfajor', 
        filter: 'Rápido',
        tipo: 'Dulce',
        ingredientes: 'Pasteleria', 
        image: require('../../assets/img/alfajor.jpg') ,
        descripcion: '¡Esta receta se compone de dos galletas rellenas de ganache de chocolate con leche de coco y cardamomo. Es fácil de ejecutar y agradará a todos. Los sándwiches de galletas son amados universalmente. Se pueden hacer con ganache, como en esta receta, pero también se pueden rellenar con cualquier cosa, desde mermelada hasta helado y más.',
        preparacion: ['Polvo de Cacao', 'Manteca', 'Coco rallado en polvo', 'Azucar blanca', 'Harina para todo uso', 'Sal', 'Leche de coco'],
    
    },

    {
        id: 17,
        category: 'sandwich', 
        name: 'Tostado', 
        filter: 'Rápido',
        tipo: 'Desayuno',
        ingredientes: 'Pan',
        image: require('../../assets/img/tostado.jpg') ,
        descripcion: 'Simplemente un sandwich de miga calentado, puede alegrarte el día',
        preparacion: ['Sandwich de miga'],
    
    },
    {
        id: 18,
        category: 'sandwich', 
        name: 'Sandwich de cerdo', 
        filter: 'Pocos ingredientes', 
        tipo: 'Almuerzo',
        ingredientes: 'Pan',
        image: require('../../assets/img/sandwichCerdo.jpg') ,
        descripcion: 'Definitivamente están sucediendo muchas cosas aquí, pero este sándwich vale la pena. Panceta de cerdo jugosa y crujiente, refrescante salsa verde y col lombarda crujiente, todo combinado en un solo sándwich.',
        preparacion: ['Harina para todo uso', 'Levadura fresca', 'Aceite de oliva', 'Sal', 'Agua tibia', 'Carne de cerdo'],
    
    },
];


export default meals;